### PR TITLE
Update releasing.md

### PR DESCRIPTION
**Pull request by kjanosz**
Make description of release process.

### CODE REVIEW

**Comment by axel22** [comment]
Awesome, thanks!

**Comment by kjanosz** [comment]
Ouch, something is broke on [releasing page](https://scalameter.github.io/home/releasing) - in preview it was looking OK. I will fix it.

**Comment by axel22** [comment]
Fixed it. Should be all good now - markdown requires an empty line when you start the bullets.

**Comment by kjanosz** [comment]
There was also other mistake. See #6 
Sorry for that.

**Comment by axel22** [comment]
No worries, merged!

**Pull request merged**
